# Generated by Django 3.2.16 on 2023-06-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='country_name',
        ),
    ]
