# Generated by Django 3.2.16 on 2023-06-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_region_country_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='emp_id',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Employment',
        ),
    ]
