# Generated by Django 3.2.16 on 2023-06-16 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_country_employment_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_name',
        ),
    ]
