# Generated by Django 3.2.16 on 2023-06-17 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_employee_emp_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country_cd',
        ),
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.RemoveField(
            model_name='region',
            name='region_cd',
        ),
        migrations.AddField(
            model_name='region',
            name='country_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employment',
            name='emp_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.employee'),
        ),
    ]
